### ISSUE TITLE
HTTPS not working

### ISSUE THREAD

**Issue by casidiablo** [paperdink/quotes#1]
Not sure why, but using `WiFiClientSecure` does not work for me. The `https.GET()` function returns `-1`.

For now I made it work by using `WiFiClient` and using `http://...`.

I am not not really sure what's going on, and it's probably outside of the scope of this project. But reporting nonetheless in case someone knows how to debug it.

**Comment by rgujju** [comment]
Which ESP32 board package version are you using? You can check it by going to `tools>Boards>Boards Manager`  in Arduino and typing ESP32 in the filter. Can you try with version 1.0.4?

![image](https://user-images.githubusercontent.com/10092220/169450418-d4cfd83a-a81d-456c-b367-9fc42ee56622.png)

**Comment by casidiablo** [comment]
I did try 1.0.4 that day, because someone reported seeing that one working. But unfortunately it didn't work for me (as in I saw the same behavior)

**Comment by pvh** [comment]
Tried. Didn't compile at all. Don't have the error messages handy but it did compile under 1.0.6. Also, it didn't work with the `http` address for me either.

**Comment by casidiablo** [comment]
@pvh even if  you replace `WiFiClientSecure` with `WiFiClient`?
